version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883

  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
      - staticfiles:/app/web/staticfiles
    depends_on:
      - django

  django:
    build: 
      context: .
      dockerfile: ./mqtt_site/django.dockerfile
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=mqtt_site
      - SQL_USER=
      - SQL_PASSWORD=
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    ports:
      - 8000:8000
    volumes:
      - ./mqtt_site:/app
      - staticfiles:/app/web/staticfiles
    command: /bin/sh -c "cd /app && python3 manage.py collectstatic --noinput && python3 manage.py makemigrations && python3 manage.py migrate && python3 /app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - mosquitto
      
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=mqtt_site

volumes:
  postgres_data:
  staticfiles:

    